name: Daily Log

on:
  push:
    branches: [dev, main]

jobs:
  log:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      DAILY_LOG_OUTPUT_PATH: tmp/daily_log.md

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Generate daily log
        run: python scripts/daily_log.py

      - name: Set date for Dropbox target path
        run: echo "TODAY=$(date +'%Y_%m_%d')" >> "$GITHUB_ENV"

      - name: Upload to Dropbox
        uses: Lewuathe/dropbox-github-action@v1.0.3
        with:
          dropbox-app-key: ${{ secrets.DROPBOX_APP_KEY }}
          dropbox-app-secret: ${{ secrets.DROPBOX_APP_SECRET }}
          dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source-path: ${{ env.DAILY_LOG_OUTPUT_PATH }}
          target-path: /logseq/Logseq_graph/journals/${{ env.TODAY }}.md
          write-mode: overwrite